name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  CXX_STANDARD: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5-dev libncursesw5-dev

    - name: Fetch FTXUI
      run: |
        git clone --branch v4.0.0 https://github.com/ArthurSonzogni/ftxui.git
        cd ftxui
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{env.CXX_STANDARD}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
